import json

OUTPUT_FILE = "../dataset/raw/synthetic/prena_synthetic.jsonl"

pairs = [
    {
        "instruction": "Buatkan press release untuk PT Nusantara Logistik tentang peluncuran layanan pengiriman same-day delivery ke 50 kota di Indonesia.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**PT Nusantara Logistik Hadirkan Layanan Same-Day Delivery ke 50 Kota, Perkuat Ekosistem E-Commerce Nasional**\n\nJAKARTA, [Tanggal] – PT Nusantara Logistik, perusahaan logistik terkemuka Indonesia, resmi meluncurkan layanan pengiriman same-day delivery yang kini menjangkau 50 kota besar di seluruh Indonesia. Ekspansi layanan ini merupakan langkah strategis perusahaan dalam mendukung pertumbuhan ekosistem e-commerce nasional yang terus berkembang pesat.\n\nDengan armada lebih dari 5.000 kurir terlatih dan jaringan hub strategis yang tersebar di seluruh kota, PT Nusantara Logistik menjamin pengiriman paket sebelum pukul 21.00 untuk setiap pesanan yang masuk sebelum pukul 12.00 siang. Layanan ini mencakup kota-kota tier 1 hingga tier 3, termasuk Bandung, Surabaya, Medan, Makassar, dan Balikpapan.\n\n\"Ini adalah milestone penting bagi kami dan bagi industri logistik Indonesia,\" ujar Direktur Operasional PT Nusantara Logistik, Budi Santoso. \"Konsumen Indonesia berhak mendapatkan layanan pengiriman yang cepat, andal, dan terjangkau. Dengan ekspansi ini, kami membuktikan bahwa kecepatan bukan lagi hak eksklusif kota besar.\"\n\nLayanan same-day delivery dapat diakses melalui aplikasi NusantaraKirim dan seluruh platform e-commerce mitra, termasuk integrasi langsung dengan lima marketplace terbesar di Indonesia.\n\n**Tentang PT Nusantara Logistik:**\nPT Nusantara Logistik adalah perusahaan logistik nasional yang berdiri sejak 2010 dengan jaringan lebih dari 500 titik layanan di Indonesia. Perusahaan melayani lebih dari 2 juta pengiriman per bulan dengan tingkat keberhasilan pengiriman 99,2%.\n\n**Kontak Media:**\nDivisi Humas PT Nusantara Logistik\nEmail: media@nusantalogistik.co.id"
    },
    {
        "instruction": "Tolong buatkan siaran pers untuk Kementerian Pendidikan tentang program beasiswa baru untuk 10.000 mahasiswa dari keluarga kurang mampu.",
        "response": "**SIARAN PERS**\n**Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi**\n**Untuk Disiarkan Segera**\n\n**Kemendikbudristek Luncurkan Program Beasiswa Harapan Bangsa untuk 10.000 Mahasiswa Kurang Mampu**\n\nJAKARTA, [Tanggal] – Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi (Kemendikbudristek) resmi meluncurkan Program Beasiswa Harapan Bangsa, sebuah inisiatif nasional yang akan memberikan dukungan penuh kepada 10.000 mahasiswa dari keluarga kurang mampu untuk menempuh pendidikan tinggi berkualitas di seluruh Indonesia.\n\nProgram ini mencakup biaya pendidikan penuh, tunjangan hidup bulanan sebesar Rp1.500.000, serta akses mentoring karier dari para profesional dan alumni berprestasi. Penerima beasiswa juga akan mendapatkan akses ke platform pembelajaran digital dan jaringan komunitas mahasiswa penerima beasiswa di seluruh perguruan tinggi negeri.\n\n\"Tidak ada satu pun anak Indonesia yang harus berhenti bermimpi karena keterbatasan ekonomi. Program Beasiswa Harapan Bangsa adalah wujud nyata komitmen pemerintah bahwa pendidikan adalah hak semua anak bangsa,\" tegas Menteri Pendidikan dalam konferensi pers peluncuran program.\n\nPendaftaran dibuka mulai [tanggal] melalui laman beasiswa.kemdikbud.go.id. Calon penerima beasiswa harus memenuhi kriteria akademik minimum IPK 3.0 dan berasal dari keluarga dengan penghasilan di bawah garis kemiskinan yang diverifikasi melalui Data Terpadu Kesejahteraan Sosial (DTKS).\n\n**Kontak Media:**\nBiro Humas Kemendikbudristek\nEmail: humas@kemdikbud.go.id\nTelepon: (021) 5711144"
    },
    {
        "instruction": "Buatkan press release untuk startup AgriTech bernama TaniDigital yang baru meluncurkan aplikasi prediksi cuaca dan harga komoditas untuk petani Indonesia.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**TaniDigital Luncurkan Aplikasi Pintar untuk Petani: Prediksi Cuaca Akurat dan Harga Komoditas Real-Time**\n\nJAKARTA, [Tanggal] – TaniDigital, startup agritech Indonesia yang berfokus pada pemberdayaan petani melalui teknologi, hari ini meluncurkan aplikasi TaniPintar — solusi digital pertama yang menggabungkan prediksi cuaca hyperlocal berbasis AI dengan informasi harga komoditas pertanian secara real-time untuk petani Indonesia.\n\nAplikasi TaniPintar menggunakan model machine learning yang dilatih dengan data cuaca dari lebih dari 2.000 stasiun meteorologi lokal, memungkinkan petani mendapatkan prediksi cuaca akurat hingga tingkat kecamatan dengan horizon 14 hari. Selain itu, fitur pemantauan harga komoditas memberikan informasi harga padi, jagung, cabai, dan 20 komoditas lainnya secara langsung dari 500 pasar tradisional di seluruh Indonesia.\n\n\"Selama ini petani kita sering dirugikan karena informasi yang tidak simetris — tengkulak tahu harga pasar, tapi petani tidak,\" jelas Andika Pratama, CEO TaniDigital. \"TaniPintar hadir untuk menyeimbangkan informasi itu. Kami ingin petani Indonesia bisa membuat keputusan bertani yang lebih cerdas, lebih untung, dan lebih sejahtera.\"\n\nAplikasi TaniPintar tersedia gratis di Google Play Store dan App Store dalam dua bahasa: Indonesia dan Jawa. TaniDigital berencana menambahkan dukungan Bahasa Sunda dan Batak pada kuartal berikutnya.\n\n**Tentang TaniDigital:**\nTaniDigital didirikan tahun 2022 oleh tim engineer dan agronomis muda Indonesia. Perusahaan telah bermitra dengan lebih dari 150 kelompok tani di 12 provinsi dan mendapatkan pendanaan awal dari Ideaosource dan Gayo Capital.\n\n**Kontak Media:**\nTim Komunikasi TaniDigital\nEmail: press@tanidigital.id"
    },
    {
        "instruction": "Bikin press release untuk PT Wijaya Karya tentang selesainya pembangunan jembatan terpanjang di Kalimantan.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**PT Wijaya Karya Rampungkan Jembatan Mahakam Agung, Jembatan Terpanjang di Kalimantan Sepanjang 2,3 Kilometer**\n\nSAMARINDA, [Tanggal] – PT Wijaya Karya (Persero) Tbk, BUMN konstruksi terkemuka Indonesia, resmi menyelesaikan pembangunan Jembatan Mahakam Agung, jembatan cable-stayed terpanjang di Pulau Kalimantan dengan bentang utama 2,3 kilometer di atas Sungai Mahakam, Samarinda, Kalimantan Timur.\n\nJembatan yang dibangun selama tiga tahun dengan nilai kontrak Rp2,8 triliun ini mampu menampung empat lajur kendaraan dan dilengkapi jalur pejalan kaki serta jalur sepeda. Dengan kapasitas beban hingga 50 ton, jembatan ini dirancang untuk mendukung mobilitas logistik dan mempercepat konektivitas antara wilayah barat dan timur Kalimantan Timur, sekaligus mendukung pengembangan Ibu Kota Nusantara (IKN).\n\n\"Jembatan Mahakam Agung adalah bukti kemampuan anak bangsa membangun infrastruktur kelas dunia di tanah sendiri,\" kata Direktur Utama PT Wijaya Karya, Harum Budiarto. \"Ini bukan sekadar jembatan — ini adalah nadi baru yang akan mengalirkan pertumbuhan ekonomi Kalimantan untuk generasi mendatang.\"\n\nJembatan ini dibangun menggunakan 85% material lokal dan melibatkan lebih dari 3.200 tenaga kerja konstruksi dari wilayah Kalimantan Timur. Proyek ini juga menerapkan standar green construction dengan sistem manajemen limbah terpadu dan pengurangan emisi karbon sebesar 30% dibandingkan metode konvensional.\n\n**Tentang PT Wijaya Karya:**\nPT Wijaya Karya (Persero) Tbk adalah BUMN konstruksi yang telah berdiri sejak 1960. Perusahaan telah membangun lebih dari 500 proyek infrastruktur besar di Indonesia dan 15 negara lainnya.\n\n**Kontak Media:**\nDivisi Corporate Communication PT Wijaya Karya\nEmail: corcom@wika.co.id"
    },
    {
        "instruction": "Perlu press release untuk brand fashion lokal Batikode yang kolaborasi dengan desainer internasional untuk koleksi batik modern.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**Batikode x Studio Marceau: Kolaborasi Bersejarah Angkat Batik Indonesia ke Panggung Mode Dunia**\n\nJAKARTA, [Tanggal] – Batikode, brand fashion lokal Indonesia yang dikenal dengan reinterpretasi batik kontemporer, hari ini mengumumkan kolaborasi eksklusif dengan Studio Marceau, rumah mode avant-garde asal Paris yang dipimpin desainer Jean-Pierre Marceau. Koleksi kapsul bertajuk \"Nusantara Nouveau\" ini akan dipamerkan pertama kali di Jakarta Fashion Week sebelum tur ke Milan dan Paris.\n\nKoleksi \"Nusantara Nouveau\" menampilkan 30 siluet ready-to-wear yang memadukan motif batik Parang, Kawung, dan Mega Mendung dengan sensibilitas estetika Eropa modern. Seluruh kain batik dalam koleksi ini diproduksi oleh pengrajin batik tulis dari Pekalongan dan Solo menggunakan teknik tradisional yang telah diwariskan selama berabad-abad.\n\n\"Bagi saya, batik Indonesia adalah salah satu warisan tekstil paling sophisticated di dunia. Bekerja sama dengan Batikode membuka mata saya akan kekayaan yang selama ini belum cukup diapresiasi secara global,\" ujar Jean-Pierre Marceau.\n\nFounderr Batikode, Sekar Ayu Rahayu, menambahkan: \"Kolaborasi ini bukan tentang mengubah batik menjadi sesuatu yang lain. Ini tentang membuktikan kepada dunia bahwa batik sudah sempurna sejak awal — ia hanya butuh panggung yang lebih besar.\"\n\nKoleksi \"Nusantara Nouveau\" akan tersedia secara terbatas di butik Batikode, boutique partner di Eropa, dan platform e-commerce premium mulai bulan depan.\n\n**Tentang Batikode:**\nBatikode didirikan tahun 2018 oleh Sekar Ayu Rahayu sebagai platform fashion yang menghubungkan pengrajin batik tradisional dengan konsumen urban modern. Brand ini telah memberdayakan lebih dari 200 pengrajin batik di Jawa.\n\n**Kontak Media:**\nPublic Relations Batikode\nEmail: pr@batikode.co.id"
    },
    {
        "instruction": "Buatkan press release untuk Rumah Sakit Cipta Husada tentang pembukaan pusat kanker baru berteknologi proton therapy pertama di Indonesia Timur.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**RS Cipta Husada Resmikan Pusat Onkologi Pertama di Indonesia Timur dengan Teknologi Proton Therapy**\n\nMAKASSAR, [Tanggal] – Rumah Sakit Cipta Husada Makassar hari ini meresmikan Pusat Onkologi Cipta Husada (POCH), fasilitas perawatan kanker pertama di kawasan Indonesia Timur yang dilengkapi teknologi proton therapy — modalitas pengobatan kanker paling presisi yang tersedia saat ini.\n\nTeknologi proton therapy memungkinkan penghancuran sel kanker dengan keakuratan tinggi, meminimalkan kerusakan jaringan sehat di sekitarnya, dan mengurangi efek samping yang umum terjadi pada kemoterapi dan radioterapi konvensional. Selama ini, pasien kanker dari kawasan timur Indonesia harus menempuh perjalanan jauh ke Jakarta atau Surabaya untuk mendapatkan akses perawatan ini.\n\n\"Dengan hadirnya POCH, pasien di Sulawesi, Maluku, Papua, dan NTT tidak perlu lagi meninggalkan keluarga dan mengeluarkan biaya besar untuk pergi ke Pulau Jawa demi mendapatkan perawatan kanker terbaik,\" tegas dr. Rahmat Hidayat, Sp.Onk, Direktur Utama RS Cipta Husada.\n\nPOCH dilengkapi dengan 45 tempat tidur rawat inap khusus onkologi, laboratorium patologi anatomi terintegrasi, serta tim dokter onkologi spesialis yang tersertifikasi internasional. Fasilitas ini juga menyediakan layanan konseling psikologis dan pendampingan survivor kanker.\n\nRS Cipta Husada bekerja sama dengan Yayasan Kanker Indonesia untuk menyediakan subsidi biaya bagi pasien kurang mampu, dengan target melayani minimal 30% pasien dari segmen non-komersial.\n\n**Kontak Media:**\nBagian Humas RS Cipta Husada\nEmail: humas@ciptahusada.co.id\nTelepon: (0411) 445566"
    },
    {
        "instruction": "Bikin press release untuk startup EdTech KelasKita yang baru mencapai 1 juta pengguna aktif dalam 18 bulan pertama.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**KelasKita Capai 1 Juta Pengguna Aktif dalam 18 Bulan, Bukti Revolusi Belajar Digital di Indonesia**\n\nJAKARTA, [Tanggal] – KelasKita, platform pembelajaran online yang berfokus pada pengembangan skill profesional berbasis industri, mengumumkan pencapaian bersejarah: 1 juta pengguna aktif dalam 18 bulan pertama sejak peluncurannya. Angka ini menjadikan KelasKita sebagai platform edtech dengan pertumbuhan pengguna tercepat yang pernah ada di Indonesia.\n\nDari 1 juta pengguna tersebut, 68% berasal dari kota-kota non-Jawa, membuktikan bahwa kebutuhan pengembangan skill profesional berkualitas tinggi tersebar merata di seluruh Indonesia. Kursus paling diminati mencakup Digital Marketing, Data Analytics, UI/UX Design, dan Full-Stack Development — keempatnya merupakan skill yang paling dicari oleh perusahaan teknologi Indonesia saat ini.\n\n\"Satu juta bukan sekadar angka bagi kami. Satu juta adalah satu juta cerita tentang seseorang yang memutuskan untuk berinvestasi pada dirinya sendiri,\" kata Nadia Kusuma, Co-Founder dan CEO KelasKita. \"Kami bangga bahwa mayoritas pengguna kami datang dari luar Jakarta — itu berarti kami benar-benar meratakan akses pendidikan berkualitas.\"\n\nKelasKita menawarkan lebih dari 300 kursus yang dikurasi bersama lebih dari 150 instruktur profesional aktif dari perusahaan teknologi ternama. Platform ini juga menyediakan fitur job placement yang telah membantu lebih dari 15.000 alumni mendapatkan pekerjaan baru atau promosi jabatan.\n\nUntuk merayakan pencapaian ini, KelasKita meluncurkan program KelasKita Satu Juta Mimpi — memberikan akses belajar gratis selama tiga bulan bagi 10.000 penerima manfaat dari daerah 3T (Tertinggal, Terdepan, Terluar).\n\n**Kontak Media:**\nKomunikasi KelasKita\nEmail: press@kelaskita.id"
    },
    {
        "instruction": "Buatkan press release untuk PT Pertamina mengenai pencapaian target bauran energi terbarukan 30% dalam operasional perusahaan.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**Pertamina Capai Target Bauran Energi Terbarukan 30% Lebih Cepat dari Jadwal, Perkuat Komitmen Net Zero 2060**\n\nJAKARTA, [Tanggal] – PT Pertamina (Persero) dengan bangga mengumumkan bahwa perusahaan telah berhasil mencapai target bauran energi terbarukan 30% dalam seluruh operasional perusahaan — dua tahun lebih awal dari target yang ditetapkan dalam Rencana Jangka Panjang Perusahaan 2025-2035.\n\nPencapaian ini diraih melalui pengembangan 12 fasilitas solar panel di kompleks kilang dan terminal BBM, pemanfaatan energi panas bumi untuk operasional gedung kantor di seluruh Indonesia, serta penerapan sistem manajemen energi berbasis AI yang berhasil meningkatkan efisiensi konsumsi energi sebesar 22% dibandingkan baseline 2020.\n\n\"Ini adalah bukti nyata bahwa transisi energi bukan hanya retorika, melainkan komitmen yang kami wujudkan dalam setiap lini operasional,\" ujar Direktur Utama PT Pertamina, Nicke Widyawati. \"Pertamina bertekad menjadi perusahaan energi kelas dunia yang bertanggung jawab terhadap planet dan masyarakat yang kami layani.\"\n\nDengan pencapaian ini, Pertamina berhasil mengurangi emisi karbon operasional sebesar 4,2 juta ton CO2 equivalent per tahun, setara dengan emisi yang diserap oleh 210 juta pohon dewasa. Perusahaan kini menetapkan target ambisius baru: bauran energi terbarukan 50% pada tahun 2030.\n\nPertamina juga mengumumkan investasi senilai Rp45 triliun untuk pengembangan infrastruktur energi terbarukan dalam lima tahun ke depan, mencakup pengembangan green hydrogen, geothermal, dan energi surya skala besar.\n\n**Kontak Media:**\nCorporate Communication PT Pertamina\nEmail: pcc@pertamina.com\nTelepon: (021) 3815111"
    },
    {
        "instruction": "Press release untuk perusahaan gaming lokal PixelNusa tentang game mobile mereka yang berhasil menembus 5 juta download di Asia Tenggara.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**PixelNusa Cetak Sejarah: Game 'Naga Pertiwi' Raih 5 Juta Download di Asia Tenggara dalam 90 Hari**\n\nJAKARTA, [Tanggal] – PixelNusa, studio game indie Indonesia, mengumumkan pencapaian luar biasa: game mobile role-playing game (RPG) bertema mitologi Nusantara mereka, 'Naga Pertiwi', telah melampaui 5 juta download di seluruh kawasan Asia Tenggara hanya dalam 90 hari sejak peluncuran global.\n\n'Naga Pertiwi' adalah game RPG yang mengangkat mitologi dan folklor dari berbagai suku bangsa Indonesia — mulai dari legenda Naga Barong dari Bali, Joko Tarub dari Jawa, hingga Putri Hijau dari Sumatera. Dengan visual hand-drawn bercita rasa wayang kontemporer dan soundtrack yang menggabungkan gamelan, kecapi, dan orkestrasi modern, game ini berhasil mencuri perhatian gamer dari Indonesia, Malaysia, Thailand, Filipina, dan Vietnam.\n\n\"Kami membuktikan bahwa konten lokal bisa bersaing di panggung global,\" kata Dimas Ardiansyah, Creative Director PixelNusa. \"Kami tidak mencoba meniru game Barat atau Jepang. Kami dengan bangga membawa kekayaan budaya Nusantara ke layar smartphone jutaan orang.\"\n\nGame ini saat ini menempati posisi Top 10 grossing game di kategori RPG di Google Play Store Indonesia, Malaysia, dan Filipina. PixelNusa mengumumkan rencana ekspansi ke pasar Jepang dan Korea Selatan pada kuartal berikutnya, bersama peluncuran ekspansi konten baru yang menampilkan legenda dari Kalimantan dan Papua.\n\n**Tentang PixelNusa:**\nPixelNusa adalah studio game indie yang didirikan tahun 2020 oleh lima alumni Institut Teknologi Bandung. Studio ini fokus mengembangkan game dengan identitas budaya Indonesia yang kuat untuk pasar global.\n\n**Kontak Media:**\nPixelNusa Communications\nEmail: media@pixelnusa.id"
    },
    {
        "instruction": "Buatin press release untuk Bank Mandiri mengenai peluncuran fitur tabungan emas digital di aplikasi Livin by Mandiri.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**Bank Mandiri Hadirkan Tabungan Emas Digital di Livin, Investasi Emas Mulai Rp5.000 untuk 23 Juta Nasabah**\n\nJAKARTA, [Tanggal] – PT Bank Mandiri (Persero) Tbk resmi meluncurkan fitur Emas Digital di aplikasi Livin by Mandiri, memungkinkan 23 juta pengguna aktif Livin untuk membeli, menjual, dan menyimpan emas digital secara mudah, aman, dan terjangkau mulai dari Rp5.000.\n\nFitur Emas Digital Livin by Mandiri menggunakan sistem backing 99,99% emas fisik yang disimpan di vault bersertifikasi LBMA (London Bullion Market Association) dan dijamin oleh Lembaga Penjamin Simpanan (LPS). Nasabah dapat bertransaksi 24 jam sehari, 7 hari seminggu, dengan harga yang transparan mengikuti harga emas dunia secara real-time.\n\n\"Emas selalu menjadi instrumen investasi favorit masyarakat Indonesia. Kini dengan Emas Digital di Livin, siapa pun bisa mulai berinvestasi emas tanpa khawatir soal keamanan penyimpanan dan dengan nominal yang sangat terjangkau,\" kata Direktur Digital dan Teknologi Bank Mandiri, Ricky Natawidjaja.\n\nPeluncuran ini sejalan dengan komitmen Bank Mandiri dalam memperluas akses layanan keuangan dan mendorong budaya menabung dan berinvestasi di kalangan masyarakat Indonesia, khususnya generasi muda. Sebagai promo peluncuran, Bank Mandiri menawarkan spread harga emas terbaik sebesar 0,5% untuk 90 hari pertama.\n\n**Tentang Bank Mandiri:**\nBank Mandiri adalah bank terbesar di Indonesia berdasarkan total aset dengan jaringan lebih dari 2.600 kantor cabang dan 18.000 ATM di seluruh Indonesia.\n\n**Kontak Media:**\nCorporate Secretary Bank Mandiri\nEmail: ir_mandiri@bankmandiri.co.id\nTelepon: (021) 5299-7777"
    },
    {
        "instruction": "Siaran pers untuk Gojek mengenai kemitraan dengan 500 UMKM kuliner lokal dalam program akselerasi GoFood.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**Gojek Gandeng 500 UMKM Kuliner Lokal dalam GoFood Akselerasi, Dorong Pendapatan Mitra Hingga 3x Lipat**\n\nJAKARTA, [Tanggal] – Gojek hari ini mengumumkan peluncuran program GoFood Akselerasi, sebuah inisiatif komprehensif yang merangkul 500 UMKM kuliner lokal terpilih dari 10 kota besar di Indonesia untuk mendapatkan dukungan menyeluruh dalam mengembangkan bisnis mereka melalui platform digital.\n\nProgram GoFood Akselerasi memberikan paket dukungan holistik yang mencakup pelatihan fotografi produk profesional, pendampingan pengelolaan menu dan penetapan harga, subsidi biaya promosi digital selama enam bulan, akses ke dapur cloud (cloud kitchen) bersubsidi, dan bimbingan sertifikasi halal dan izin usaha. Berdasarkan pilot program yang dijalankan bersama 50 UMKM di Jakarta dan Surabaya, mitra yang mengikuti program ini mengalami peningkatan pendapatan rata-rata 3x lipat dalam tiga bulan.\n\n\"UMKM kuliner adalah jantung ekonomi lokal Indonesia. Ketika mereka bertumbuh, seluruh komunitas ikut merasakan manfaatnya,\" kata Chief Food Officer Gojek, Siti Rahmawati. \"GoFood Akselerasi adalah bentuk nyata komitmen kami bahwa teknologi harus menjadi jembatan, bukan hambatan, bagi pelaku usaha kecil.\"\n\nPendaftaran program terbuka bagi UMKM kuliner yang telah beroperasi minimal enam bulan dan memiliki NPWP aktif. Seleksi dilakukan berdasarkan potensi produk, komitmen pelaku usaha, dan dampak sosial terhadap komunitas lokal.\n\n**Kontak Media:**\nHumas Gojek\nEmail: press@gojek.com"
    },
    {
        "instruction": "Bikin press release untuk PT PLN tentang program elektrifikasi 1.000 desa terpencil menggunakan panel surya.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**PLN Terangi 1.000 Desa Terpencil dengan Energi Surya, 250.000 Keluarga Nikmati Listrik untuk Pertama Kalinya**\n\nJAKARTA, [Tanggal] – PT PLN (Persero) resmi menyelesaikan Program Listrik Surya Desa, sebuah proyek elektrifikasi masif yang berhasil membawa listrik untuk pertama kalinya ke 1.000 desa terpencil di 15 provinsi Indonesia, menerangi lebih dari 250.000 keluarga.\n\nProgram yang berjalan selama dua tahun ini menggunakan sistem Pembangkit Listrik Tenaga Surya (PLTS) off-grid yang dilengkapi baterai penyimpanan berkapasitas tinggi, memastikan pasokan listrik tersedia 24 jam penuh bahkan di daerah yang tidak terjangkau jaringan listrik konvensional. Setiap instalasi mampu menyuplai listrik untuk 200-300 rumah tangga beserta fasilitas umum seperti sekolah, puskesmas, dan masjid.\n\n\"Listrik bukan kemewahan — listrik adalah hak setiap warga negara Indonesia. Hari ini, 250.000 keluarga yang selama puluhan tahun hidup dalam gelap akhirnya bisa menikmati cahaya,\" kata Direktur Utama PLN, Darmawan Prasodjo, dengan penuh haru saat meresmikan instalasi terakhir di Desa Timur Jaya, Papua.\n\nDampak elektrifikasi ini telah dirasakan langsung: angka kehadiran siswa di sekolah meningkat 40%, usaha mikro tumbuh 65% setelah memiliki akses listrik, dan layanan kesehatan di puskesmas setempat kini dapat beroperasi optimal dengan peralatan medis bertenaga listrik.\n\nPLN berkomitmen untuk melanjutkan program serupa dengan target 500 desa tambahan pada tahun mendatang, dengan fokus pada wilayah Papua, Maluku, dan Nusa Tenggara Timur.\n\n**Kontak Media:**\nCorporate Communication PLN\nEmail: contact-pln@pln.co.id\nTelepon: 123"
    },
    {
        "instruction": "Press release untuk brand skincare Lacuna Beauty tentang peluncuran lini produk ramah lingkungan dengan kemasan biodegradable.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**Lacuna Beauty Luncurkan 'EcoGlow Line' — Skincare Efektif, Kemasan 100% Biodegradable**\n\nJAKARTA, [Tanggal] – Lacuna Beauty, brand skincare lokal Indonesia yang dikenal dengan formula berbasis bahan aktif alami, hari ini meluncurkan EcoGlow Line — lini produk perawatan kulit terbaru yang menggabungkan efektivitas klinis premium dengan komitmen lingkungan melalui kemasan 100% biodegradable dan formula bebas dari 27 bahan kimia berbahaya.\n\nEcoGlow Line terdiri dari delapan produk perawatan kulit — mulai dari serum vitamin C, moisturizer SPF 30, hingga eye cream — yang seluruh kemasannya dibuat dari bahan PHA (Polyhydroxyalkanoates) yang dapat terurai secara alami dalam 12 bulan di kondisi tanah biasa, tanpa meninggalkan mikroplastik. Selain itu, setiap pembelian EcoGlow Line akan berkontribusi pada program penanaman mangrove di pesisir Sulawesi Selatan bersama Yayasan Bahari Lestari.\n\n\"Kecantikan sejati tidak datang dengan mengorbankan planet kita,\" ujar Founder Lacuna Beauty, Tasya Maharani. \"Kami percaya bahwa konsumen modern tidak ingin memilih antara kulit sehat dan bumi yang sehat. EcoGlow Line hadir sebagai jawaban bahwa keduanya bisa dan harus berjalan beriringan.\"\n\nSeluruh formula EcoGlow Line telah mendapatkan sertifikasi dermatologist-tested, BPOM approved, Halal MUI, dan Cruelty-Free dari PETA. Produk tersedia secara eksklusif di lacunabeauty.id dan Sociolla mulai pekan ini.\n\n**Tentang Lacuna Beauty:**\nLacuna Beauty didirikan tahun 2019 dengan misi menghadirkan skincare premium berbahan alami Indonesia yang terjangkau. Saat ini brand telah memiliki lebih dari 500.000 pelanggan setia.\n\n**Kontak Media:**\nHumas Lacuna Beauty\nEmail: pr@lacunabeauty.id"
    },
    {
        "instruction": "Tolong buatkan press release untuk Tokopedia mengenai fitur baru cicilan tanpa bunga untuk produk elektronik.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**Tokopedia Luncurkan TokoInstall — Cicilan 0% Tanpa Kartu Kredit untuk Produk Elektronik Pilihan**\n\nJAKARTA, [Tanggal] – Tokopedia, platform e-commerce terkemuka Indonesia, memperkenalkan TokoInstall — fitur cicilan tanpa bunga (0%) khusus untuk produk elektronik yang kini bisa dinikmati oleh semua pengguna Tokopedia, bahkan tanpa memiliki kartu kredit.\n\nTokoInstall menggunakan teknologi credit scoring berbasis AI yang menganalisis riwayat transaksi pengguna di ekosistem Tokopedia untuk menentukan limit cicilan secara instan dan aman. Pengguna yang memenuhi syarat dapat mencicil produk elektronik senilai hingga Rp15.000.000 dalam tenor 3, 6, atau 12 bulan tanpa bunga dan tanpa biaya admin tersembunyi.\n\n\"Selama ini cicilan identik dengan kartu kredit yang tidak semua orang punya. TokoInstall mengubah itu. Kami ingin smartphone terbaru, laptop untuk belajar, atau kulkas untuk keluarga tidak lagi harus menunggu tabungan terkumpul,\" jelas Chief Marketing Officer Tokopedia, Melissa Sanjaya.\n\nFitur TokoInstall tersedia untuk lebih dari 2 juta produk elektronik dari 50.000 toko partner terpilih di Tokopedia, mencakup smartphone, laptop, tablet, peralatan rumah tangga, dan kamera. Tokopedia menanggung seluruh biaya bunga, tanpa beban apapun kepada pembeli maupun penjual.\n\nSebagai penawaran peluncuran, pengguna yang bertransaksi pertama kali menggunakan TokoInstall dalam 30 hari ke depan akan mendapatkan cashback sebesar 10% hingga Rp500.000.\n\n**Kontak Media:**\nPublic Relations Tokopedia\nEmail: media@tokopedia.com"
    },
    {
        "instruction": "Press release untuk perusahaan startup HealthTech MedikuAI tentang AI diagnostic tool untuk deteksi dini diabetes.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**MedikuAI Luncurkan Teknologi AI Deteksi Dini Diabetes dengan Akurasi 94,3%, Revolusi Skrining Kesehatan Indonesia**\n\nBANDUNG, [Tanggal] – MedikuAI, startup healthtech Indonesia yang berbasis di Bandung, hari ini memperkenalkan DiaCek — sistem kecerdasan buatan untuk deteksi dini diabetes tipe 2 yang telah mendapatkan izin edar Kementerian Kesehatan dan mencatatkan akurasi diagnostik 94,3% dalam uji klinis multicenter yang melibatkan 12 rumah sakit di Indonesia.\n\nDiaCek menganalisis kombinasi data sederhana yang dapat dikumpulkan tanpa peralatan laboratorium mahal: foto retina dari kamera smartphone standar, data riwayat gejala yang diinputkan pasien, dan empat pengukuran biometrik dasar. Dalam 15 menit, sistem memberikan laporan risiko diabetes yang komprehensif beserta rekomendasi langkah tindak lanjut.\n\n\"Indonesia adalah salah satu negara dengan jumlah penderita diabetes tertinggi di dunia, dan 60% di antaranya tidak terdiagnosis,\" kata dr. Kevin Surya, Co-Founder dan Chief Medical Officer MedikuAI. \"DiaCek hadir untuk mengubah angka itu. Kami membawa skrining diabetes berkualitas tinggi ke puskesmas di pedesaan yang tidak memiliki laboratorium canggih.\"\n\nDiaCek saat ini sedang diimplementasikan di 150 puskesmas di Jawa Barat dalam program percontohan bersama Dinas Kesehatan Provinsi Jawa Barat. Target MedikuAI adalah menjangkau 5.000 fasilitas kesehatan primer di seluruh Indonesia pada akhir 2026.\n\n**Tentang MedikuAI:**\nMedikuAI didirikan tahun 2021 oleh tim dokter dan engineer alumni ITB dan Universitas Padjadjaran. Perusahaan telah menerima pendanaan dari Sequoia Southeast Asia dan MDI Ventures.\n\n**Kontak Media:**\nHumas MedikuAI\nEmail: press@medikuai.id"
    },
    {
        "instruction": "Buatkan press release untuk Telkom Indonesia tentang peluncuran jaringan 5G di 10 kota baru.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**Telkom Indonesia Perluas Jaringan 5G ke 10 Kota Baru, Akselerasi Transformasi Digital Nasional**\n\nJAKARTA, [Tanggal] – PT Telkom Indonesia (Persero) Tbk mengumumkan ekspansi jaringan 5G IndiHome & Telkomsel ke 10 kota baru di Indonesia, memperluas cakupan layanan 5G nasional menjadi 25 kota dengan total populasi terlayani lebih dari 80 juta jiwa.\n\nSepuluh kota baru yang kini menikmati layanan 5G meliputi Batam, Pekanbaru, Pontianak, Banjarmasin, Manado, Kendari, Ambon, Jayapura, Kupang, dan Mataram. Ekspansi ini merupakan bagian dari investasi infrastruktur digital Telkom senilai Rp28 triliun yang dialokasikan untuk tahun ini, dengan fokus pemerataan konektivitas digital ke kawasan Indonesia Timur dan kepulauan.\n\n\"Visi Indonesia Digital 2045 bukan mimpi yang akan tercapai sendiri. Dibutuhkan infrastruktur yang merata dan handal dari Sabang sampai Merauke,\" tegas Direktur Utama Telkom Indonesia, Ririek Adriansyah. \"Ekspansi 5G ini bukan hanya soal kecepatan internet — ini tentang membuka pintu bagi inovasi di sektor kesehatan, pendidikan, pertanian, dan industri di seluruh pelosok Indonesia.\"\n\nDengan kecepatan unduh rata-rata 1,2 Gbps dan latensi di bawah 10 milidetik, jaringan 5G Telkom mendukung pengembangan smart city, telemedicine, autonomous vehicle, dan berbagai aplikasi industri 4.0. Telkom juga mengumumkan 15 kerja sama baru dengan pemerintah daerah, universitas, dan pelaku industri untuk mengembangkan use case 5G lokal.\n\n**Kontak Media:**\nCorporate Communication Telkom Indonesia\nEmail: corporate.communication@telkom.co.id\nTelepon: (021) 5215109"
    },
    {
        "instruction": "Buatkan press release untuk perusahaan properti Sentosa Realty tentang proyek apartemen terjangkau bagi milenial di pinggiran Jakarta.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**Sentosa Realty Hadirkan Urban Nest: 2.000 Unit Apartemen Mulai Rp300 Juta untuk Milenial Pekerja Jakarta**\n\nDEPOK, [Tanggal] – PT Sentosa Realty Tbk hari ini meluncurkan Urban Nest Depok, proyek hunian vertikal pertama mereka yang secara khusus dirancang untuk memenuhi kebutuhan dan aspirasi generasi milenial dan Gen Z yang bekerja di Jakarta namun tidak terjangkau membeli properti di pusat kota.\n\nUrban Nest Depok akan menghadirkan 2.000 unit apartemen studio hingga dua kamar dengan harga mulai Rp300 juta, berlokasi 200 meter dari Stasiun LRT Depok yang memiliki konektivitas langsung ke Sudirman dan Kuningan. Desain proyek ini mengusung konsep \"Live-Work-Play\" dengan menyediakan co-working space 24 jam, gym, rooftop garden, dan area komunitas aktif yang mendorong interaksi sosial.\n\n\"Kami mendengar generasi muda — mereka tidak mau berkompromi antara lokasi strategis dan harga yang masuk akal. Urban Nest adalah jawaban kami: hunian layak, koneksi transportasi prima, dan komunitas yang vibrant, dengan harga yang bisa dijangkau dengan gaji UMR+,\" kata Direktur Pengembangan Sentosa Realty, Haryo Wibisono.\n\nPembelian dapat dilakukan dengan skema KPA (Kredit Pemilikan Apartemen) melalui 8 bank mitra dengan uang muka mulai 5% dan cicilan mulai Rp1,8 juta per bulan. Sentosa Realty juga bekerja sama dengan BPJS Ketenagakerjaan untuk memfasilitasi pemanfaatan dana JHT sebagai uang muka.\n\nUnit perdana akan diserahterimakan pada kuartal pertama 2028. Pendaftaran early bird dengan harga spesial dibuka mulai hari ini di urbannestkita.id.\n\n**Kontak Media:**\nPublic Relations Sentosa Realty\nEmail: pr@sentosarealty.co.id\nTelepon: (021) 7867890"
    },
    {
        "instruction": "Siaran pers untuk organisasi nirlaba Yayasan Melek Digital tentang program pelatihan literasi digital untuk ibu rumah tangga di desa.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**Yayasan Melek Digital Latih 50.000 Ibu Rumah Tangga Desa Menjadi Wirausaha Digital dalam Program Emak-Emak Go Digital**\n\nYOGYAKARTA, [Tanggal] – Yayasan Melek Digital Indonesia hari ini mengumumkan Program Emak-Emak Go Digital, sebuah inisiatif pelatihan literasi dan kewirausahaan digital yang menargetkan 50.000 ibu rumah tangga di 500 desa di Pulau Jawa, Bali, dan Nusa Tenggara.\n\nProgram ini hadir sebagai respons atas kesenjangan digital yang masih mencolok di pedesaan Indonesia, di mana ibu rumah tangga seringkali menjadi kelompok yang paling tertinggal dalam adopsi teknologi digital. Pelatihan mencakup penggunaan smartphone untuk keperluan produktif, pengelolaan media sosial untuk promosi produk, penggunaan platform e-commerce untuk berjualan, dan manajemen keuangan digital dasar.\n\n\"Ketika seorang ibu melek digital, dampaknya bukan hanya bagi dirinya sendiri — ia akan mengajarkan anak-anaknya, membantu tetangganya, dan menjadi penggerak ekonomi produktif di desanya,\" ujar Ketua Yayasan Melek Digital, Sri Mulyani Rahma.\n\nProgram berlangsung selama tiga bulan dengan format pelatihan tatap muka seminggu sekali dan pendampingan online melalui grup WhatsApp. Setiap peserta mendapatkan modul pelatihan cetak, akses ke platform pembelajaran digital selama satu tahun, dan sertifikat kompetensi digital yang diakui oleh Badan Nasional Sertifikasi Profesi (BNSP).\n\nYayasan Melek Digital bermitra dengan Kementerian Desa PDTT, Telkomsel, dan Google.org dalam pelaksanaan program ini. Pendaftaran terbuka bagi ibu rumah tangga usia 18-55 tahun yang berdomisili di desa sasaran program.\n\n**Kontak Media:**\nHumas Yayasan Melek Digital\nEmail: humas@melekdigital.or.id\nTelepon: (0274) 889900"
    },
    {
        "instruction": "Buatkan press release untuk PT Kereta Api Indonesia tentang peluncuran layanan kereta cepat rute Surabaya-Malang.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**KAI Luncurkan Kereta Cepat Surabaya-Malang, Tempuh 90 Kilometer Hanya dalam 35 Menit**\n\nSURABAYA, [Tanggal] – PT Kereta Api Indonesia (Persero) hari ini secara resmi meluncurkan layanan Kereta Cepat Surabaya-Malang (KCSM), moda transportasi massal berteknologi tinggi yang memangkas waktu tempuh antara Surabaya dan Malang dari 2 jam menjadi hanya 35 menit.\n\nKCSM menggunakan rangkaian Electric Multiple Unit (EMU) generasi terbaru buatan industri dalam negeri yang mampu melaju hingga 250 km/jam. Dengan kapasitas 450 penumpang per rangkaian dan frekuensi 24 perjalanan pulang-pergi per hari, KCSM ditargetkan melayani 15.000 penumpang setiap harinya.\n\n\"Ini adalah hari bersejarah bagi mobilitas Jawa Timur. Surabaya dan Malang kini bukan lagi dua kota yang terpisah macet — mereka menjadi satu koridor metropolitan yang terintegrasi,\" kata Direktur Utama KAI, Didiek Hartantyo, dalam upacara peresmian yang dihadiri oleh Gubernur Jawa Timur.\n\nStasiun keberangkatan KCSM terhubung langsung dengan moda transportasi lain melalui konsep Transit-Oriented Development (TOD): di Surabaya terintegrasi dengan LRT Surabaya dan halte BRT, sementara di Malang tersambung dengan angkutan perkotaan dan layanan ojek online. Harga tiket ditetapkan mulai Rp85.000 untuk kelas ekonomi dan Rp145.000 untuk kelas bisnis.\n\nKonstruksi KCSM menggunakan 78% komponen buatan dalam negeri, menjadikannya proyek kereta cepat dengan tingkat TKDN (Tingkat Komponen Dalam Negeri) tertinggi yang pernah ada di Indonesia.\n\n**Kontak Media:**\nHumas PT KAI\nEmail: humas@kai.id\nTelepon: 121"
    },
    {
        "instruction": "Press release untuk startup CleanTech SuryaBersih yang berhasil mengembangkan panel surya berbahan lokal yang efisiensinya meningkat 40% dari generasi sebelumnya.",
        "response": "**SIARAN PERS**\n**Untuk Disiarkan Segera**\n\n**SuryaBersih Ciptakan Panel Surya Berbahan Lokal dengan Efisiensi 40% Lebih Tinggi, Terobosan Energi Hijau Indonesia**\n\nBANDUNG, [Tanggal] – SuryaBersih, startup cleantech Indonesia berbasis di Bandung, mengumumkan terobosan teknologi yang berpotensi mengubah peta energi terbarukan di Indonesia: panel surya generasi terbaru mereka, SuryaPanel X3, mencatatkan efisiensi konversi energi 28,7% — meningkat 40% dibandingkan panel surya generasi sebelumnya — menggunakan bahan baku silikon yang sebagian besar bersumber dari tambang lokal di Kalimantan.\n\nSuryaPanel X3 menggunakan teknologi sel surya perovskite-silicon tandem yang dikembangkan secara mandiri oleh tim riset SuryaBersih selama tiga tahun, berkolaborasi dengan Institut Teknologi Bandung dan BRIN (Badan Riset dan Inovasi Nasional). Dengan efisiensi ini, luas instalasi panel yang dibutuhkan untuk menghasilkan output energi yang sama dapat dikurangi hingga 30%, secara signifikan menurunkan biaya instalasi total.\n\n\"Selama ini Indonesia mengimpor hampir 90% panel surya yang kita pasang di tanah sendiri. SuryaPanel X3 adalah langkah nyata menuju kemandirian energi surya Indonesia,\" jelas Dr. Farhan Aziz, CTO SuryaBersih dan peneliti utama proyek ini. \"Kami membuktikan bahwa inovasi teknologi energi tidak harus datang dari luar negeri.\"\n\nSuryaPanel X3 telah mendapatkan sertifikasi dari International Electrotechnical Commission (IEC) dan Badan Standardisasi Nasional (BSN). Produksi massal dijadwalkan dimulai pada kuartal ketiga tahun ini dengan kapasitas awal 100 megawatt peak (MWp) per tahun di fasilitas manufaktur baru di Karawang.\n\nSuryaBersih telah menandatangani perjanjian pembelian dengan tiga perusahaan utilitas energi terbarukan di Indonesia senilai total Rp380 miliar.\n\n**Tentang SuryaBersih:**\nSuryaBersih adalah startup cleantech yang didirikan tahun 2020 dengan misi mempercepat transisi energi Indonesia melalui inovasi panel surya buatan lokal. Perusahaan telah mendapat pendanaan dari MDGI dan East Ventures.\n\n**Kontak Media:**\nKomunikasi SuryaBersih\nEmail: media@suryabersih.id"
    }
]

with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
    for pair in pairs:
        entry = {
            "category": "press_release",
            "messages": [
                {"role": "user", "content": pair["instruction"]},
                {"role": "assistant", "content": pair["response"]}
            ]
        }
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")

print(f"Done! {len(pairs)} pairs appended to {OUTPUT_FILE}")
